#!/bin/bash

## Run cmake if there's no build directory
if [ ! -d "pathfinder-build" ]; then
    ./runcmake
fi

cd pathfinder-build

## Build
make

## Run tests after build
if [ -f "TestAll" ]; then
    ./TestAll
fi
