#ifndef DEMO_CONFIGURATIONS_H
#define DEMO_CONFIGURATIONS_H

const int NUMBER_OF_NODES_IN_A_ROW = 30;

const int NUMBER_OF_NODES_IN_A_COLUMN = NUMBER_OF_NODES_IN_A_ROW;

const int WINDOW_WIDTH = 650;

const int WINDOW_HEIGHT = 650;

const float BLOCK_WIDTH = WINDOW_WIDTH / (float)NUMBER_OF_NODES_IN_A_ROW;

const float BLOCK_HEIGHT = WINDOW_HEIGHT / (float)NUMBER_OF_NODES_IN_A_COLUMN;

const bool RANDOM_WALLS = false;

#endif
