#!/bin/bash

## Run cmake if there's no build directory
if [ ! -d "pathfinder-demo-build" ]; then
    ./runcmake
fi

## Install path finder library if it doesn't exist
if [ ! -d "../libPathFinder" ]; then
    cd ..
    ./install
    cd pathfinder-demo
fi

## Install SFML if it doesn't exist in the project
if [ ! -d "SFML" ]; then
    ./installSFML
fi

cd pathfinder-demo-build

## Build
make
