#!/bin/bash

if [ ! -d "SFML" ]; then
  mkdir SFML
fi

cd SFML/

if [ ! -d "SFML-2.3"]; then
  wget https://github.com/SFML/SFML/archive/2.3.tar.gz
  tar -xvxf 2.3.tar.gz 
fi

cmake SFML-2.3/
make
cp -r SFML-2.3/include .
