#!/bin/bash

## Run cmake and build if there's no executable for pathfinderDemo
if [ ! -f "pathfinder-demo-build/pathfinderDemo" ]; then
    ./runcmake
    ./build
fi

## Run tests
if [ -f "pathfinder-demo-build/pathfinderDemo" ]; then
    pathfinder-demo-build/pathfinderDemo
fi
